repo_url: https://github.com/spaghetticookbook/website
repo_name: Spaghetti Cookbook Website
edit_uri: edit/main/docs

site_name: Spaghetti Cookbook
site_url: https://spaghetticookbook.com
site_description: Awesome cookbook for AI engineers.
site_author: Spaghetti Cookbook
site_image: https://staging.fullstackdeeplearning.com/images/opengraph.png
site_image_alt: Image explaining what Spaghetti Cookbook covers.

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/spaghetticookbook"  target="_blank" rel="noopener">Spaghetti Cookbook</a>
theme:
  features:
    - navigation.tabs
    - content.code.annotation
    - content.code.copy
    - toc.integrate
    - search.suggest
    - content.tabs.link
    # - search.highlight
    # - navigation.tabs.sticky
    # - navigation.sections
  font: false
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/spaghetticookbook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@The_Full_Stack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bakedpotatocookbook/posts/
